name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Full depth (not shallow) for better relevancy of Sonar analysis

      - name: Use .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      - run: pwd

      # Begin ci-build.ps1
      - name: dotnet restore
        run: dotnet restore

      - name: dotnet build
        run: dotnet build -c release --no-restore

      - name: dotnet pack
        run: dotnet pack -c release --no-build
      # End ci-build.ps1

      - run: ls -R artifacts

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: dotnet nuget push
        if: ${{ github.ref == 'refs/heads/main' }}
        run: >-
          dotnet nuget push
          artifacts/package/release/*.nupkg
          --api-key $NUGET_AUTH_TOKEN
          --no-symbols
          --skip-duplicate
          --source https://api.nuget.org/v3/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.NUGET_AUTH_TOKEN }}
